#pragma once

// Include all files helps keep main.cpp cleaner
#include <Math/Math.h>
#include <Graphics/Window.h>
#include <Graphics/Shader.h>
#include <Utils/FileUtils.h>
#include <Renderer/Renderer2d.h>
#include <Renderer/SimpleRenderer.h>
#include <Renderer/BatchRenderer.h>
#include <Renderer/Sprite.h>
#include <Renderer/StaticSprite.h>
#include <Graphics/Layers/TileLayer.h>
#include <Graphics/Layers/Layer.h>
#include <Graphics/Label.h>
#include <Graphics/Layers/Group.h>
#include <Graphics/Font/Font.h>
#include <Graphics/Font/FontManager.h>
#include <Graphics/Texture.h>
#include <Graphics/TextureManager.h>
#include <Utils/Timer.h>
#include <Graphics/Camera.h>
#include <Utils/MapEditor.h>
#include <Graphics/Buffers/FrameBuffer.h>
#include <EngineEditor/Editor.h>
#include <Renderer/Scene2D.h>
#include <Renderer/Scene3D.h>
#include <Renderer/3DRenderer/Renderer3D.h>
#include <Renderer/3DRenderer/BatchRenderer3D.h>
#include <Renderer/3DRenderer/Renderable3D.h>
#include <Renderer/3DRenderer/Cube.h>
#include <Graphics/Camera3D.h>