#pragma once

// Include all files helps keep main.cpp cleaner
#include <Math/Math.h>
#include <Graphics/Window.h>
#include <Graphics/Shader.h>
#include <Utils/FileUtils.h>
#include <Renderer/BatchRenderer.h>
#include <Renderer/Sprite.h>
#include <Graphics/Layers/TileLayer.h>
#include <Graphics/Layers/Layer.h>
#include <Graphics/Label.h>
#include <Graphics/Layers/Group.h>
#include <Graphics/Font/Font.h>
#include <Graphics/Font/FontManager.h>
#include <Graphics/Texture.h>
#include <Graphics/TextureManager.h>
#include <Utils/Timer.h>
#include <Graphics/Camera.h>
#include <Graphics/Buffers/FrameBuffer.h>
#include <EngineEditor/Editor.h>
#include <Renderer/3DRenderer/Cube.h>
#include <Graphics/Camera3D.h>
#include <Scripting/ScriptEngine.h>
#include <Scripting/ScriptSystem.h>
#include <Scripting/ScriptGlue.h>
#include <Entity/Components.h>
#include <Entity/ComponentManager.h>
#include <Entity/Entity.h>
#include <Core/Logger.h>